name: Deploy to Cloud Run
on:
  push:
    branches:
      - main # Cambia esto si usas otra rama
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker
      
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/calculadora .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/calculadora
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: calculadora
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/calculadora
          region: ${{ secrets.GCP_REGION }}
          allow-unauthenticated: true