name: Deploy to Cloud Run
on:
  push:
    branches:
      - main # Cambia esto si usas otra rama
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker
      
      - name: Build and push Docker image
        run: |
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          # Eliminar cualquier espacio en blanco
          PROJECT_ID=$(echo "$PROJECT_ID" | tr -d ' ')
          IMAGE_NAME="gcr.io/${PROJECT_ID}/calculadora"
          docker build -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"
      
      - name: Deploy to Cloud Run
        uses: google